# Generated by Django 5.1.3 on 2024-11-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tictactoe_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="winner",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
