# Generated by Django 5.1.3 on 2024-12-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tictactoe_app", "0002_game_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="board_ary",
            field=models.CharField(default=" , , , , , , , , ", max_length=200),
        ),
    ]
