# Generated by Django 5.1.3 on 2025-01-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tictactoe_app", "0003_alter_game_board_ary"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="locked_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
